import { FunctionalityType } from "./enums";

export const functionalityList = [
  {group: FunctionalityType.reduceDisease, no: '1-1', label: '골다골증 발생 위험 감소에 도움을 줌'},
  {group: FunctionalityType.reduceDisease, no: '1-2', label: '충치발생위험감소에 도움을 줌'},
  {group: FunctionalityType.nutrient, no: '2-1', label: '갑상선 호르몬의 합성에 필요'},
  {group: FunctionalityType.nutrient, no: '2-2', label: '결합조직 형성과 기능유지에 필요'},
  {group: FunctionalityType.nutrient, no: '2-3', label: '근육, 결합조직 등 신체조직의 구성성분'},
  {group: FunctionalityType.nutrient, no: '2-4', label: '단백질 및 아미노산 이용에 필요'},
  {group: FunctionalityType.nutrient, no: '2-5', label: '뼈 형성에 필요'},
  {group: FunctionalityType.nutrient, no: '2-6', label: '뼈와 치아 형성에 필요'},
  {group: FunctionalityType.nutrient, no: '2-7', label: '뼈의 구성에 필요'},
  {group: FunctionalityType.nutrient, no: '2-8', label: '뼈의 형성과 유지에 필요'},
  {group: FunctionalityType.nutrient, no: '2-9', label: '산화·환원 효소의 활성에 필요'},
  {group: FunctionalityType.nutrient, no: '2-10', label: '상피세포의 성장과 발달에 필요'},
  {group: FunctionalityType.nutrient, no: '2-11', label: '세포와 혈액생성에 필요'},
  {group: FunctionalityType.nutrient, no: '2-12', label: '식이섬유 보충'},
  {group: FunctionalityType.nutrient, no: '2-13', label: '신경과 근육 기능 유지에 필요'},
  {group: FunctionalityType.nutrient, no: '2-14', label: '신경발달에 필요'},
  {group: FunctionalityType.nutrient, no: '2-15', label: '어두운 곳에서 시각 적응을 위해 필요'},
  {group: FunctionalityType.nutrient, no: '2-16', label: '에너지 생성에 필요'},
  {group: FunctionalityType.nutrient, no: '2-17', label: '에너지 이용에 필요'},
  {group: FunctionalityType.nutrient, no: '2-18', label: '에너지, 포도당, 지질의 합성에 필요'},
  {group: FunctionalityType.nutrient, no: '2-19', label: '유해산소로부터 세포를 보호하는데 필요'},
  {group: FunctionalityType.nutrient, no: '2-20', label: '정상적인 면역기능에 필요'},
  {group: FunctionalityType.nutrient, no: '2-21', label: '정상적인 세포분열에 필요'},
  {group: FunctionalityType.nutrient, no: '2-22', label: '정상적인 엽산 대사에 필요'},
  {group: FunctionalityType.nutrient, no: '2-23', label: '정상적인 혈액응고에 필요'},
  {group: FunctionalityType.nutrient, no: '2-24', label: '지방, 탄수화물, 단백질 대사와 에너지 생성에 필요'},
  {group: FunctionalityType.nutrient, no: '2-25', label: '철의 운반과 이용에 필요'},
  {group: FunctionalityType.nutrient, no: '2-26', label: '철의 흡수에 필요'},
  {group: FunctionalityType.nutrient, no: '2-27', label: '체내 물과 전해질 균형에 필요'},
  {group: FunctionalityType.nutrient, no: '2-28', label: '체내 산소운반과 혈액생성에 필요'},
  {group: FunctionalityType.nutrient, no: '2-29', label: '체내 에너지 생성에 필요'},
  {group: FunctionalityType.nutrient, no: '2-30', label: '체내 필수 영양성분이나 활성물질의 운반과 저장에 필요'},
  {group: FunctionalityType.nutrient, no: '2-31', label: '체액, 산-염기의 균형 유지에 필요'},
  {group: FunctionalityType.nutrient, no: '2-32', label: '칼슘과 인이 흡수되고 이용되는데 필요'},
  {group: FunctionalityType.nutrient, no: '2-33', label: '탄수화물과 에너지 대사에 필요'},
  {group: FunctionalityType.nutrient, no: '2-34', label: '태아 신경관의 정상 발달에 필요'},
  {group: FunctionalityType.nutrient, no: '2-35', label: '피부와 점막을 형성하고 기능을 유지하는데 필요'},
  {group: FunctionalityType.nutrient, no: '2-36', label: '필수지방산의 보충'},
  {group: FunctionalityType.nutrient, no: '2-37', label: '혈액의 호모시스테인 수준을 정상으로 유지하는데 필요'},
  {group: FunctionalityType.nutrient, no: '2-38', label: '효소, 호르몬, 항체의 구성에 필요'},
  {group: FunctionalityType.nutrient, no: '2-39', label: '체내 탄수화물, 지방, 단백질 대사에 관여'},
  {group: FunctionalityType.nutrient, no: '2-40', label: '항산화 작용을 하여 유해산소로부터 세포를 보호하는데 필요'},
  {group: FunctionalityType.physiology, no: '3-1', label: '장 건강'},
  {group: FunctionalityType.physiology, no: '3-2', label: '혈당 조절'},
  {group: FunctionalityType.physiology, no: '3-3', label: '관절/뼈 건강'},
  {group: FunctionalityType.physiology, no: '3-4', label: '혈중 콜레스테롤 개선'},
  {group: FunctionalityType.physiology, no: '3-5', label: '체지방 감소'},
  {group: FunctionalityType.physiology, no: '3-6', label: '면역기능개선'},
  {group: FunctionalityType.physiology, no: '3-7', label: '항산화'},
  {group: FunctionalityType.physiology, no: '3-8', label: '피부 건강'},
  {group: FunctionalityType.physiology, no: '3-9', label: '혈압 조절'},
  {group: FunctionalityType.physiology, no: '3-10', label: '혈중 중성지방 개선'},
  {group: FunctionalityType.physiology, no: '3-11', label: '혈행개선'},
  {group: FunctionalityType.physiology, no: '3-12', label: '기억력 개선'},
  {group: FunctionalityType.physiology, no: '3-13', label: '간 건강'},
  {group: FunctionalityType.physiology, no: '3-14', label: '눈 건강'},
  {group: FunctionalityType.physiology, no: '3-15', label: '긴장완화'},
  {group: FunctionalityType.physiology, no: '3-16', label: '인지능력 향상'},
  {group: FunctionalityType.physiology, no: '3-17', label: '전립선 건강'},
  {group: FunctionalityType.physiology, no: '3-18', label: '칼슘 흡수 촉진'},
  {group: FunctionalityType.physiology, no: '3-19', label: '운동수행 능력'},
  {group: FunctionalityType.physiology, no: '3-20', label: '요로 건강'},
  // {group: FunctionalityType.physiology, no: '3-21', label: '치아 건강'},
  {group: FunctionalityType.physiology, no: '3-22', label: '피로개선'},
  {group: FunctionalityType.physiology, no: '3-23', label: '갱년기 남성 건강'},
  {group: FunctionalityType.physiology, no: '3-24', label: '갱년기 여성 건강'},
  {group: FunctionalityType.physiology, no: '3-25', label: '과민 피부 상태 개선'},
  {group: FunctionalityType.physiology, no: '3-26', label: '배뇨기능개선'},
  {group: FunctionalityType.physiology, no: '3-27', label: '위 건강/소화기능'},
  {group: FunctionalityType.physiology, no: '3-28', label: '정자 운동성'},
  {group: FunctionalityType.physiology, no: '3-29', label: '여성 질 건강'},
  {group: FunctionalityType.physiology, no: '3-30', label: '월경전 상태 개선'},
  {group: FunctionalityType.physiology, no: '3-31', label: '어린이 성장 발육'},
  {group: FunctionalityType.physiology, no: '3-32', label: '수면질 개선'},
  {group: FunctionalityType.physiology, no: '3-33', label: '근력 개선'},
  {group: FunctionalityType.physiology, no: '3-34', label: '구강 건강'},
];
