import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { FC, useEffect, useRef } from 'react';
import { Input } from '@chakra-ui/input';
import { Button } from '@chakra-ui/button';
import ky from 'ky';
import { useRouter } from 'next/router';
import useSWR from 'swr';
import { Spinner } from '@chakra-ui/spinner';

const Login: FC<{}> = () => {
  const router = useRouter();

  const usernameRef = useRef<HTMLInputElement>(null);
  const passwordRef = useRef<HTMLInputElement>(null);

  const loginHandler = async () => {
    const username = usernameRef?.current?.value;
    const password = passwordRef?.current?.value;

    try {
      const result = await ky.put(`/api/users/login`, {json: {username, password}}).json();
      router.push('/');
    } catch (err: any) {
      console.log(err.message);
      if (err.message === 'Request failed with status code 401 Unauthorized') return;
    }
  };
  const {data, error} = useSWR(`/api/users`);

  useEffect(() => {
    if (data && !error) router.push('/');
  }, [data, error])

  return error ? <div className={styles.container}>
    <div id="modal"></div>
    <Head>
      <title>Food uploader</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Input placeholder="Username" ref={usernameRef} />
    <Input type="password" placeholder="Password" ref={passwordRef} />
    <Button colorScheme="teal" onClick={loginHandler}>로그인</Button>
  </div> : <Spinner
    thickness="4px"
    speed="0.65s"
    emptyColor="gray.200"
    color="blue.500"
    size="xl"
  />;
};

export default Login;